# @package _global_

hydra:
  run:
    # Output directory for normal run
#    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
    dir: .

job:
  data:
    add_coords_to_raw:
      prepare_data_ccur: 0
      add_coords_to_raw_nc: 0
    select_reunion: 0
    merge_reu: 0
    mergetime_swio: 0
    missing_reu: 0
    select_moufia: 0
  moufia:
    reallocation: 1
    regroup: 1
    statistics: 1
    correlations:
      mean_annual_cycle: 1


dir:
  working: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/iCARE_cloud/
  data: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/iCARE_cloud/dataset
  local_data: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/iCARE_cloud/local_data
  plot: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/iCARE_cloud/plot
  icare_data_local: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/iCARE_cloud/local_data/icare_dir_ccur
  icare_data_ccur: /gpfs/scratch/le2p/OBS_DATA/icare/ctang

param:
  plot_big_data_test: 1
  ct_dict: {'1': 'clearsky', '5': 'vLow', '6': 'Low', '7': 'Med', '8': 'HOp', '9': 'vHOp', '11': 'sTp'}


file:
  icare_CT_MSG0415: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/iCARE_cloud/local_data/S_NWC_CT_MSG1_globeI-VISIR_20170827T120000Z.nc
  ct_icare_CT_MSG0415: /Users/ctang/Microsoft_OneDrive/OneDrive/CODE/iCARE_cloud/local_data/icare_dir_ccur/ct.S_NWC_CT_MSG1_globeI-VISIR_20190101T060000Z.nc
  icare_3km_lat_MSG0415: ./local_data/coords/MSG+0415.3km.lat
  icare_3km_lon_MSG0415: ./local_data/coords/MSG+0415.3km.lon

  reu_localtime_2017_2022: ./dataset/ct.S_NWC_CT_MSG1_globeI-VISIR_201706-202206.lonlat.reu.yearly.local_time.nc

  moufia_nc: ./local_data/ct.S_NWC_CT_MSG1_globeI-VISIR_201706-202202.lonlat.moufia.yearly.nc
  moufia_local_time: ./local_data/ct.S_NWC_CT_MSG1_globeI-VISIR_201706-202206.lonlat.moufia.yearly.local_time

  moufia_reallocation: ./local_data/ct.S_NWC_CT_MSG1_globeI-VISIR_201706-202206.lonlat.moufia.yearly.local_time.reallocation
  moufia_reallocation_regroup: ./local_data/ct.S_NWC_CT_MSG1_globeI-VISIR_201706-202206.lonlat.moufia.yearly.local_time.reallocation.regroup

  ct_moufia_monthly_occurrence_plot: ./plot/ct_monthly_moufia_occurrence_201706-202206.png
  ct_moufia_hourly_occurrence_plot: ./plot/ct_hourly_moufia_occurrence_201706-202206.png

  gillot_rg_mf_2019: ./dataset/RG-2019_Gillot.csv

#plot:
#
#output:








